[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "halfhop"
version = "0.1.0"
description = "Half-Hop Graph Neural Networks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torch_geometric",
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "scikit-learn",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["halfhop*"]
